# Generated by Django 3.2.12 on 2022-02-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouser',
            name='fname',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ouser',
            name='lname',
            field=models.CharField(default='', max_length=122),
        ),
    ]
