# Generated by Django 3.2.12 on 2022-03-03 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ouser',
            name='profile_photo',
        ),
    ]
