# Generated by Django 3.2.12 on 2022-03-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
