# Generated by Django 3.2.12 on 2022-02-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20220223_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouser',
            name='time_stamp',
            field=models.TimeField(auto_now=True),
        ),
    ]
