# Generated by Django 3.2.12 on 2022-03-19 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_ouser_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ouser',
            name='is_online',
        ),
    ]
