# Generated by Django 3.2.12 on 2022-03-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_ouser_is_busy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouser',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
    ]
