# Generated by Django 3.2.12 on 2022-02-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_alter_ouser_time_stamp'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ouser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='ouser',
            name='email',
            field=models.EmailField(max_length=155, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ouser',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
