# Generated by Django 3.2.12 on 2022-02-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20220223_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouser',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ouser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
