# Generated by Django 3.2.12 on 2022-02-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20220224_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouser',
            name='profile_photo',
            field=models.ImageField(default='icons8-test-account.svg', upload_to='images/'),
        ),
    ]
