# Generated by Django 3.2.12 on 2022-05-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsettings',
            name='enable_transcriptions',
            field=models.IntegerField(default=0),
        ),
    ]
