# Generated by Django 3.2.12 on 2022-03-17 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220317_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calllog',
            name='incoming',
        ),
    ]
