# Generated by Django 3.2.12 on 2022-03-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_calllog_incoming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='missed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
