# Generated by Django 3.2.12 on 2022-03-25 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_remove_ouser_is_online'),
        ('app', '0004_auto_20220317_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSettings',
            fields=[
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to='landing.ouser')),
                ('enable_predictions', models.BooleanField(default=False)),
            ],
        ),
    ]
